{% set name = "camel-converter" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/camel_converter-{{ version }}.tar.gz
  sha256: 06a9d357c185749bae9618352ba89b6a7f4ea920122d125d10582045b736c565

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
  run_constrained:
    - pydantic >=1.8.2

test:
  imports:
    - camel_converter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanders41/camel-converter
  summary: Converts a string from snake case to camel case or camel case to snake case
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
